repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: local
    hooks:
      - id: tsc
        name: tsc
        entry: bun run tsc --noEmit
        language: system
        pass_filenames: false
        stages: [commit]
      - id: lint
        name: lint
        entry: bun run lint
        language: system
        pass_filenames: false
        stages: [commit]
