database:
  host: localhost
  port: 27017
  name: boom
  max_pool_size: 200
  replica_set: null
  username: mongoadmin
  password: mongoadminsecret
  srv: false
redis:
  host: localhost
  port: 6379
workers:
  ZTF:
    command_interval: 500
    alert:
      n_workers: 1
    ml:
      n_workers: 1
    filter:
      n_workers: 1
  LSST:
    command_interval: 500
    alert:
      n_workers: 1
    ml:
      n_workers: 0
    filter:
      n_workers: 1
crossmatch:
  LSST: []
  ZTF:
    - catalog: PS1_DR1
      radius: 2.0 # 2 arcseconds
      use_distance: false
      projection:
        _id: 1
        gMeanPSFMag: 1
        gMeanPSFMagErr: 1
        rMeanPSFMag: 1
        rMeanPSFMagErr: 1
        iMeanPSFMag: 1
        iMeanPSFMagErr: 1
        zMeanPSFMag: 1
        zMeanPSFMagErr: 1
        yMeanPSFMag: 1
        yMeanPSFMagErr: 1
        ra: 1
        dec: 1
    - catalog: Gaia_DR3
      radius: 2.0 # 2 arcseconds
      use_distance: false
      projection:
        _id: 1
        parallax: 1
        parallax_error: 1
        phot_g_mean_mag: 1
        phot_bp_mean_mag: 1
        phot_rp_mean_mag: 1
        ra: 1
        dec: 1
    - catalog: milliquas_v6
      radius: 2.0 # 2 arcseconds
      use_distance: false
      projection:
        _id: 1
        Name: 1
        Descrip: 1
        Qpct: 1
        ra: 1
        dec: 1
    - catalog: NED
      radius: 300.0 # 300 arcseconds
      use_distance: true
      distance_key: "z"
      distance_max: 30.0
      distance_max_near: 300.0
      projection: 
        _id: 0
        ra: 1
        dec: 1
        objname: 1
        objtype: 1
        z: 1
        z_unc: 1
        z_tech: 1
        z_qual: 1
        DistMpc: 1
        DistMpc_unc: 1
        ebv: 1
        m_Ks: 1
        m_Ks_unc: 1
        tMASSphot: 1
        Mstar: 1
        Mstar_unc: 1