[package]
name = "boom-config"
version = "0.1.0"
edition = "2021"
description = "Configuration management for BOOM"

[dependencies]
config = "0.15.6"
dotenvy = "0.15.7"
regex = "1.11.0"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.20.0"
thiserror = "2.0.11"
tracing = "0.1.41"
