use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

// NOTE: GENERATED BY CLAUDE, NEED TO TEST!!

/// Realtime alert metrics from OTel: survey name, current alert count, and timestamp when gathered.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct RealtimeAlertMetrics {
    pub survey: String,
    pub n_alerts: u32,
    pub gathered_at: i64, // unix timestamp in seconds
}

/// Parse Prometheus-format metrics from OTel Collector and extract alert counts.
///
/// Looks for metrics matching the pattern `boom_alerts_total{survey="..."}` and
/// extracts the survey name and alert count from each line. Attaches the gathered_at
/// timestamp to each metric.
pub fn parse_otel_metrics(text: &str, gathered_at: i64) -> Result<Vec<RealtimeAlertMetrics>, String> {
    let mut metrics = Vec::new();

    for line in text.lines() {
        // Skip comments and empty lines
        if line.starts_with('#') || line.is_empty() {
            continue;
        }

        // Look for metrics with "alerts" in the name (e.g., boom_alerts_total)
        if !line.contains("alerts") {
            continue;
        }

        // Parse lines like: boom_alerts_total{survey="ztf",instance="..."} 1234
        if let Some((metric_part, value_part)) = line.split_once(' ') {
            // Extract survey name from labels
            if let Some(survey) = extract_survey_label(metric_part) {
                // Try to parse the numeric value
                match value_part.trim().parse::<u32>() {
                    Ok(n_alerts) => {
                        metrics.push(RealtimeAlertMetrics {
                            survey,
                            n_alerts,
                            gathered_at,
                        });
                    }
                    Err(_) => {
                        // Skip lines that don't have valid numeric values
                        continue;
                    }
                }
            }
        }
    }

    if metrics.is_empty() {
        // Return empty list rather than error — OTel may not have metrics yet
        return Ok(Vec::new());
    }

    Ok(metrics)
}

/// Extract the survey label value from a Prometheus metric line.
///
/// Parses labels like `metric_name{survey="ztf",other="value"}` and returns "ztf".
fn extract_survey_label(metric_part: &str) -> Option<String> {
    if let Some(start) = metric_part.find("survey=\"") {
        let after_key = &metric_part[start + 8..];
        if let Some(end) = after_key.find('"') {
            return Some(after_key[..end].to_string());
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_single_metric() {
        let text = "boom_alerts_total{survey=\"ztf\",instance=\"localhost\"} 42\n";
        let result = parse_otel_metrics(text, 1234567890).unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].survey, "ztf");
        assert_eq!(result[0].n_alerts, 42);
        assert_eq!(result[0].gathered_at, 1234567890);
    }

    #[test]
    fn test_parse_multiple_metrics() {
        let text = r#"# HELP boom_alerts_total Total alerts
# TYPE boom_alerts_total counter
boom_alerts_total{survey="ztf",instance="localhost"} 42
boom_alerts_total{survey="atlas",instance="localhost"} 100
"#;
        let result = parse_otel_metrics(text, 1234567890).unwrap();
        assert_eq!(result.len(), 2);
        assert_eq!(result[0].survey, "ztf");
        assert_eq!(result[0].n_alerts, 42);
        assert_eq!(result[1].survey, "atlas");
        assert_eq!(result[1].n_alerts, 100);
    }

    #[test]
    fn test_skip_comments_and_empty_lines() {
        let text = r#"# HELP boom_alerts_total
# TYPE boom_alerts_total counter

boom_alerts_total{survey="ztf"} 10
"#;
        let result = parse_otel_metrics(text, 1234567890).unwrap();
        assert_eq!(result.len(), 1);
    }

    #[test]
    fn test_skip_non_alert_metrics() {
        let text = r#"other_metric{instance="localhost"} 5
boom_alerts_total{survey="ztf"} 42
boom_latency_ms{instance="localhost"} 100
"#;
        let result = parse_otel_metrics(text, 1234567890).unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].survey, "ztf");
    }

    #[test]
    fn test_empty_metrics() {
        let text = "# HELP boom_alerts_total\n# TYPE boom_alerts_total counter\n";
        let result = parse_otel_metrics(text, 1234567890).unwrap();
        assert_eq!(result.len(), 0);
    }

    #[test]
    fn test_extract_survey_label() {
        assert_eq!(
            extract_survey_label("boom_alerts_total{survey=\"ztf\",instance=\"localhost\"}"),
            Some("ztf".to_string())
        );
        assert_eq!(
            extract_survey_label("boom_alerts_total{instance=\"localhost\",survey=\"atlas\"}"),
            Some("atlas".to_string())
        );
        assert_eq!(extract_survey_label("boom_alerts_total{instance=\"localhost\"}"), None);
    }
}
