use serde::{Deserialize, Serialize};
use utoipa::ToSchema;
use actix_web::{get, web, HttpResponse};
use tracing::{error, debug};

// NOTE: GENERATED BY CLAUDE, NEED TO TEST!!

/// Realtime alert metrics from OTel: survey name, current alert count, and timestamp when gathered.
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct RealtimeAlertMetrics {
    /// Name of the survey (e.g., "ztf", "atlas")
    pub survey: String,
    /// Total number of alerts currently recorded for this survey
    pub n_alerts: u32,
    /// Unix timestamp in seconds when these metrics were gathered from OTel Collector
    pub gathered_at: i64,
}

/// Parse Prometheus-format metrics from OTel Collector and extract alert counts.
///
/// Looks for metrics matching the pattern `boom_alerts_total{survey="..."}` and
/// extracts the survey name and alert count from each line. Attaches the gathered_at
/// timestamp to each metric.
pub fn parse_otel_metrics(text: &str, gathered_at: i64) -> Result<Vec<RealtimeAlertMetrics>, String> {
    let mut metrics = Vec::new();

    for line in text.lines() {
        // Skip comments (lines starting with #) and empty lines
        if line.starts_with('#') || line.is_empty() {
            continue;
        }

        // Look for metrics with "alerts" in the name (e.g., boom_alerts_total)
        // This filters out unrelated metrics like latency, throughput, etc.
        if !line.contains("alerts") {
            continue;
        }

        // Parse lines like: boom_alerts_total{survey="ztf",instance="..."} 1234
        // Split on the first whitespace to separate metric definition from value
        if let Some((metric_part, value_part)) = line.split_once(' ') {
            // Extract survey name from labels (e.g., survey="ztf")
            if let Some(survey) = extract_survey_label(metric_part) {
                // Try to parse the numeric value as a u32
                match value_part.trim().parse::<u32>() {
                    Ok(n_alerts) => {
                        // Successfully parsed: add this metric to our results
                        metrics.push(RealtimeAlertMetrics {
                            survey,
                            n_alerts,
                            gathered_at,
                        });
                    }
                    Err(_) => {
                        // Skip lines that don't have valid numeric values
                        continue;
                    }
                }
            }
        }
    }

    if metrics.is_empty() {
        // Return empty list rather than error — OTel may not have metrics yet
        // This is not an error condition, just means no alerts are recorded
        return Ok(Vec::new());
    }

    Ok(metrics)
}

/// Extract the survey label value from a Prometheus metric line.
///
/// Parses labels like `metric_name{survey="ztf",other="value"}` and returns "ztf".
/// This function handles labels in any order.
fn extract_survey_label(metric_part: &str) -> Option<String> {
    // Look for the pattern: survey="
    if let Some(start) = metric_part.find("survey=\"") {
        // Move past the `survey="` part (8 characters)
        let after_key = &metric_part[start + 8..];
        // Find the closing quote
        if let Some(end) = after_key.find('"') {
            // Extract the value between the quotes and return as owned String
            return Some(after_key[..end].to_string());
        }
    }
    None
}

/// Fetch realtime alert metrics from OTel Collector Prometheus endpoint.
///
/// This endpoint:
/// 1. Checks if OTel collection is enabled in the config
/// 2. Constructs the full URL to the OTel Collector's metrics endpoint
/// 3. Makes an HTTP GET request to fetch Prometheus-format metrics
/// 4. Parses the response to extract alert metrics per survey
/// 5. Returns structured JSON with survey names and alert counts
///
/// # Examples
/// - GET /babamul/stats/realtime
/// - Returns: [{"survey": "ztf", "n_alerts": 42, "gathered_at": 1234567890}]
#[utoipa::path(
    get,
    path = "/babamul/stats/realtime",
    responses(
        (status = 200, description = "Realtime alert metrics retrieved successfully from OTel Collector", body = Vec<RealtimeAlertMetrics>),
        (status = 500, description = "Failed to fetch or parse metrics from OTel Collector"),
        (status = 503, description = "OTel Collector is not enabled or is unreachable")
    ),
    tags=["Babamul", "Stats"]
)]
#[get("/stats/realtime")]
pub async fn get_realtime_stats(
    /// Application configuration containing OTel collector settings
    config: web::Data<crate::conf::AppConfig>,
    /// HTTP client for making requests to OTel Collector
    client: web::Data<reqwest::Client>,
) -> HttpResponse {
    // --- STEP 1: Validate that OTel is enabled ---
    if !config.otel.enabled {
        debug!("OTel Collector is disabled; returning 503 Service Unavailable");
        return HttpResponse::ServiceUnavailable().json(serde_json::json!({
            "error": "OTel Collector is not enabled"
        }));
    }

    // --- STEP 2: Build the full URL to OTel Collector metrics endpoint ---
    // Example: http://localhost:8888/metrics
    let url = format!(
        "http://{}:{}{}",
        config.otel.host, config.otel.port, config.otel.metrics_endpoint
    );

    debug!("Fetching metrics from OTel Collector: {}", url);

    // --- STEP 3: Make HTTP GET request to OTel Collector ---
    match client.get(&url).send().await {
        Ok(response) => {
            // HTTP request succeeded; now read the response body
            match response.text().await {
                Ok(text) => {
                    // Successfully read response body as text
                    debug!("Received {} bytes from OTel Collector", text.len());

                    // --- STEP 4: Parse Prometheus-format metrics ---
                    let gathered_at = flare::Time::now().to_utc().timestamp();
                    match parse_otel_metrics(&text, gathered_at) {
                        Ok(metrics) => {
                            // Successfully parsed metrics
                            debug!("Parsed {} alert metrics from OTel response", metrics.len());
                            // Return the metrics as JSON with 200 OK status
                            HttpResponse::Ok().json(metrics)
                        }
                        Err(e) => {
                            // Parsing failed (malformed Prometheus response)
                            error!("Failed to parse OTel metrics: {}", e);
                            HttpResponse::InternalServerError().json(serde_json::json!({
                                "error": "Failed to parse metrics response",
                                "details": e
                            }))
                        }
                    }
                }
                Err(e) => {
                    // Failed to read response body (network/IO error)
                    error!("Failed to read OTel response body: {}", e);
                    HttpResponse::InternalServerError().json(serde_json::json!({
                        "error": "Failed to read metrics response",
                        "details": e.to_string()
                    }))
                }
            }
        }
        Err(e) => {
            // HTTP request failed (connection refused, DNS error, etc.)
            error!("Failed to connect to OTel Collector at {}: {}", url, e);
            HttpResponse::ServiceUnavailable().json(serde_json::json!({
                "error": "OTel Collector unreachable",
                "details": e.to_string()
            }))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_single_metric() {
        let text = "boom_alerts_total{survey=\"ztf\",instance=\"localhost\"} 42\n";
        let result = parse_otel_metrics(text, 1234567890).unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].survey, "ztf");
        assert_eq!(result[0].n_alerts, 42);
        assert_eq!(result[0].gathered_at, 1234567890);
    }

    #[test]
    fn test_parse_multiple_metrics() {
        let text = r#"# HELP boom_alerts_total Total alerts
# TYPE boom_alerts_total counter
boom_alerts_total{survey="ztf",instance="localhost"} 42
boom_alerts_total{survey="atlas",instance="localhost"} 100
"#;
        let result = parse_otel_metrics(text, 1234567890).unwrap();
        assert_eq!(result.len(), 2);
        assert_eq!(result[0].survey, "ztf");
        assert_eq!(result[0].n_alerts, 42);
        assert_eq!(result[1].survey, "atlas");
        assert_eq!(result[1].n_alerts, 100);
    }

    #[test]
    fn test_skip_comments_and_empty_lines() {
        let text = r#"# HELP boom_alerts_total
# TYPE boom_alerts_total counter

boom_alerts_total{survey="ztf"} 10
"#;
        let result = parse_otel_metrics(text, 1234567890).unwrap();
        assert_eq!(result.len(), 1);
    }

    #[test]
    fn test_skip_non_alert_metrics() {
        let text = r#"other_metric{instance="localhost"} 5
boom_alerts_total{survey="ztf"} 42
boom_latency_ms{instance="localhost"} 100
"#;
        let result = parse_otel_metrics(text, 1234567890).unwrap();
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].survey, "ztf");
    }

    #[test]
    fn test_empty_metrics() {
        let text = "# HELP boom_alerts_total\n# TYPE boom_alerts_total counter\n";
        let result = parse_otel_metrics(text, 1234567890).unwrap();
        assert_eq!(result.len(), 0);
    }

    #[test]
    fn test_extract_survey_label() {
        assert_eq!(
            extract_survey_label("boom_alerts_total{survey=\"ztf\",instance=\"localhost\"}"),
            Some("ztf".to_string())
        );
        assert_eq!(
            extract_survey_label("boom_alerts_total{instance=\"localhost\",survey=\"atlas\"}"),
            Some("atlas".to_string())
        );
        assert_eq!(extract_survey_label("boom_alerts_total{instance=\"localhost\"}"), None);
    }
}
