name: Create and publish Docker images

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for API image
        id: meta_api
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-api

      - name: Extract metadata (tags, labels) for scheduler image
        id: meta_scheduler
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-scheduler

      - name: Build and push API image
        id: push_api
        uses: docker/build-push-action@v6
        with:
          context: .
          target: api
          push: true
          tags: ${{ steps.meta_api.outputs.tags }}
          labels: ${{ steps.meta_api.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push scheduler image
        id: push_scheduler
        uses: docker/build-push-action@v6
        with:
          context: .
          target: scheduler
          push: true
          tags: ${{ steps.meta_scheduler.outputs.tags }}
          labels: ${{ steps.meta_scheduler.outputs.labels }}
          platforms: linux/amd64,linux/arm64

      # This step generates an artifact attestation for the image,
      # which is an unforgettable statement about where and how it was built
      # It increases supply chain security for people who consume the image.
      - name: Generate artifact attestation for API image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}-api
          subject-digest: ${{ steps.push_api.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for scheduler image
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}-scheduler
          subject-digest: ${{ steps.push_scheduler.outputs.digest }}
          push-to-registry: true
