name: Deploy to production

concurrency: production

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (tag, branch, or commit SHA)"
        required: true
        default: "main"
        type: string

jobs:
  deploy:
    environment: production
    runs-on:
      - self-hosted
      - production
    env:
      ENVIRONMENT: production
      DOMAIN: ${{ vars.DOMAIN }}
      BOOM_DATABASE__HOST: ${{ vars.BOOM_DATABASE__HOST }}
      BOOM_DATABASE__PASSWORD: ${{ secrets.BOOM_DATABASE__PASSWORD }}
      BOOM_API__AUTH__SECRET_KEY: ${{ secrets.BOOM_API__AUTH__SECRET_KEY }}
      BOOM_API__AUTH__ADMIN_USERNAME: ${{ vars.BOOM_API__AUTH__ADMIN_USERNAME }}
      BOOM_API__AUTH__ADMIN_EMAIL: ${{ vars.BOOM_API__AUTH__ADMIN_EMAIL }}
      BOOM_API__AUTH__ADMIN_PASSWORD: ${{ secrets.BOOM_API__AUTH__ADMIN_PASSWORD }}
      STACK_NAME: boom
      PROMETHEUS_USER: ${{ vars.PROMETHEUS_USER }}
      PROMETHEUS_HASHED_PASSWORD: ${{ secrets.PROMETHEUS_HASHED_PASSWORD }}
      KAFKA_ADMIN_PASSWORD: ${{ secrets.KAFKA_ADMIN_PASSWORD }}
      KAFKA_READONLY_PASSWORD: ${{ secrets.KAFKA_READONLY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.inputs.version || github.ref }}
      - run: >
          docker compose --profile prod
          -f docker-compose.yaml build
      - run: >
          docker compose --profile prod
          -f docker-compose.yaml up -d
