apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack
    receivers:
      - uid: slack-default
        type: slack
        settings:
          url: ${SLACK_WEBHOOK_URL}
          title: '{{ template "slack.title" . }}'
          text: '{{ template "slack.message" . }}'
        disableResolveMessage: false
